### ISSUE TITLE
Please add upgrade guide for v3 and improve README

### ISSUE THREAD

**Issue by PikachuEXE** [collectiveidea/interactor#61]
Some changes are not well explained like:
- Abort execution immediately upon interactor failure
- Remove "magical" access to the context through the interactor

Also `run!` is not mentioned in README

Thank you for your hard work, I like `interactor` very much :)
## TODO
- [x] Add code documentation
- [ ] Write upgrade guide
- [ ] Describe halting behavior of `fail!`

**Comment by laserlemon** [comment]
Closing because… stale. ☹️
